### ISSUE TITLE
Performance analysis of secp521r1

### ISSUE THREAD

**Issue by shobhitJava** [starkbank/ecdsa-java#12]
Hi Team

Thanks for sharing your work in public. I took the code and added specification for NIST secp521r1 curve in the code and ,measured the performance for (ECDSA) Signature Verification. I got around 400 Signature verification.

Also when I saw your performance for secp256k1 curve

Library                    | sign          | verify

java.security           | 0.9ms       | 2.4ms
starkbank-ecdsa    | 4.3ms       | 9.9ms

If I am correct. The java.security is performing 4 times better than your version?
Any thoughts

**Comment by cdottori-stark** [comment]
Hi shobhitJava,

Our main goals for this [family of libraries](https://github.com/starkbank?q=ecdsa) were the creation of ECDSA sign/verify tools with very simple interfaces and setups, so we focused:
- Externally: on the development of intuitive interfaces that could be replicated to many different languages with minimal adaptations (translatability);
- Internally: on ease of maintenance, translatability, minimal external dependencies;

Although desirable, performance was a secondary focus, since at least concerning our web-based use cases, a few more milliseconds wouldn't be relevant for web requests involving database reads, etc.

That being said, any suggestions aiming to enhance the performance of any of our libraries would be most welcome!

Thank you for your interest!
