### ISSUE TITLE
Private Key string representation

### ISSUE THREAD

**Issue by sulqadari** [starkbank/ecdsa-java#14]
I just tried to get string representation of the Secret key and have got unexpected result:
Both methods:
`ByteString bStr	= privateKey.toByteString();`
`String res		= BinaryAscii.hexFromBinary(bStr);`

and:
`String res = privateKey.secret.toString(16);`

return some thing like this:

`4b2e90b5a1044c47853924d138c033bf0ff8c73ec0bce4bef513c75ae5e57ddb0c` 
which differs in length with expected size (32 bytes) by one byte.

Explanations of correct use are highly appreciated.
Kind regards.

**Comment by leandro-stark** [comment]
Hi, @sulqadari!

It's expected that the difference between the two methods will be of exactly one byte, because, while the toString() operator on the integer only returns the hexadecimal encoding of the the private key secret, the toByteString() function returns the length of the curve PLUS the private key secret.
Just to illustrate, when you call the toByteString function it calls the stringFromNumber:

``` java
public ByteString toByteString() {
    return BinaryAscii.stringFromNumber(this.secret, this.curve.length());
}
```

and this function returns the concatenated secret and curve length:

``` java
public static ByteString stringFromNumber(BigInteger number, int length) {
    String fmtStr = "%0" + String.valueOf(2 * length) + "x";
    String hexString = String.format(fmtStr, number);
    return new ByteString(BinaryAscii.binaryFromHex(hexString));
}
```

So, this extra byte actually refers to the length of the curve.

If you have any questions, do not hesitate to ask!

Best,
